# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IRF_compute <- function(beta, B, hor, nvar, plag) {
    .Call('_VARS_IRF_compute', PACKAGE = 'VARS', beta, B, hor, nvar, plag)
}

FEVD_compute <- function(Sigma, B, Psi, nvar, hor) {
    .Call('_VARS_FEVD_compute', PACKAGE = 'VARS', Sigma, B, Psi, nvar, hor)
}

HDC <- function(start, end, shock, res_var, IRF, eps) {
    .Call('_VARS_HDC', PACKAGE = 'VARS', start, end, shock, res_var, IRF, eps)
}

HDC_ts <- function(start, end, shock, res_var, IRF, eps) {
    .Call('_VARS_HDC_ts', PACKAGE = 'VARS', start, end, shock, res_var, IRF, eps)
}

#' @details compute HD of all shocks to which_var from start to end.
get_HDs <- function(start, end, which_var, IRF, eps) {
    .Call('_VARS_get_HDs', PACKAGE = 'VARS', start, end, which_var, IRF, eps)
}

#' @details compute HD of all shocks to which_var from start to start, start + 1, ..., end.
#' @return a matrix, of which row j is HD of shock j to which_var during the given period (a time series)
get_HDs_ts <- function(start, end, which_var, IRF, eps) {
    .Call('_VARS_get_HDs_ts', PACKAGE = 'VARS', start, end, which_var, IRF, eps)
}

bootstrap_c <- function(Y_start, beta, u, IV, identify, method, save, T) {
    .Call('_VARS_bootstrap_c', PACKAGE = 'VARS', Y_start, beta, u, IV, identify, method, save, T)
}

IRF_compute_batch <- function(beta_draw, B_draw, hor) {
    .Call('_VARS_IRF_compute_batch', PACKAGE = 'VARS', beta_draw, B_draw, hor)
}

FEVD_compute_batch <- function(beta_draw, B_draw, Sigma_draw, Psi_draw, hor) {
    .Call('_VARS_FEVD_compute_batch', PACKAGE = 'VARS', beta_draw, B_draw, Sigma_draw, Psi_draw, hor)
}

HDs_compute_batch <- function(start, end, which_var, IRF_draw, eps_draw) {
    .Call('_VARS_HDs_compute_batch', PACKAGE = 'VARS', start, end, which_var, IRF_draw, eps_draw)
}

gibbs_sampler <- function(Y, X, priors, burn_in = 100L, draw = 1000L, thin = 1L, post_save = 500L, post_method = 0L) {
    .Call('_VARS_gibbs_sampler', PACKAGE = 'VARS', Y, X, priors, burn_in, draw, thin, post_save, post_method)
}

impose_SR_and_EBR <- function(alpha_post, Sigma_post, restrictions, Y, X, draw, plag, hor) {
    .Call('_VARS_impose_SR_and_EBR', PACKAGE = 'VARS', alpha_post, Sigma_post, restrictions, Y, X, draw, plag, hor)
}

impose_NSR <- function(restrictions, Y, X, B_draw, beta_draw, Sigma_draw, plag, hor, M) {
    .Call('_VARS_impose_NSR', PACKAGE = 'VARS', restrictions, Y, X, B_draw, beta_draw, Sigma_draw, plag, hor, M)
}

construct_data <- function(Y_start, beta, u, T) {
    .Call('_VARS_construct_data', PACKAGE = 'VARS', Y_start, beta, u, T)
}

